spring.application.name=CadastroClube
# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIG FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===============================
# jwt / jey
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiracao=14400000

# ===============================
# EMAIL
# ===============================
resend.api-key=${RESEND_API_KEY}

# ===============================
# APP
# ===============================
app.frontend-url=${FRONTEND_URL}
app.mail.from=${MAIL_FROM}

# ===============================
# IMAGEM
# ===============================
supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket-socios=${SUPABASE_BUCKET_SOCIOS:socios}
supabase.bucket-dependentes=${SUPABASE_BUCKET_DEPENDENTES:dependentes}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB