CREATE TABLE usuarios (
    id BIGSERIAL PRIMARY KEY,
    imagem_url VARCHAR(255),
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    permissao VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL
);